### ISSUE TITLE
Missing MIT license in PIP index

### ISSUE THREAD

**Issue by piotrm-nvidia** [delfick/alt-pytest-asyncio#14]
PIP index entry doesn't contain valid ``License`` entry.

## Reproduction

1. Install ``alt-pytest-asyncio`` at Ubuntu 20.04:
    ```
    pip install alt-pytest-asyncio
    ```
2. Print ``alt-pytest-asyncio`` license
    ```
    pip show alt-pytest-asyncio
    ```
## Expected result

```
Name: alt-pytest-asyncio
Version: 0.7.0
Summary: Alternative pytest plugin to pytest-asyncio
Home-page: 
Author: 
Author-email: Stephen Moore <delfick755@gmail.com>
License: MIT #<--- MIT SHOULD be HERE
```
## Actual result
```
Name: alt-pytest-asyncio
Version: 0.7.0
Summary: Alternative pytest plugin to pytest-asyncio
Home-page: 
Author: 
Author-email: Stephen Moore <delfick755@gmail.com>
License:       #<--- MIT SHOULD be HERE
```

Also PyPi page in Meta section doesn't display MIT license.

**Comment by delfick** [comment]
<img width="1397" alt="Screenshot 2023-06-23 at 3 35 08 pm" src="https://github.com/delfick/alt-pytest-asyncio/assets/109301/1ee0aa06-4b3f-49a2-bd59-babba8930813">

0.7.1 has been released with your fix. Thanks :)
