### ISSUE TITLE
Disable 10 second timeout when debugging

### ISSUE THREAD

**Issue by Aran-Fey** [delfick/alt-pytest-asyncio#16]
It's impossible to debug async tests with this plugin because they always get cancelled after 10 seconds. Would it be possible to detect that a debugger is running and automatically disable the timeout?

**Comment by delfick** [comment]
Hi,

Yeah, that can be annoying. I tend to solve the problem by giving the test
I'm debugging a @pytest.mark.async_timeout(1e10).

I don't think it'd be possible to know if a debugger has already started,
and even then the way a timeout interrupts a task means I don't think you'd
be able to solve the problem that way anyways.

**Comment by Aran-Fey** [comment]
I tried my hand at it and it seems like a trivial fix. All I had to do was change this function:

    def timeout_task(task):
        if not task.done():
            info["cancelled"] = True
            task.cancel()

to this:

    def timeout_task(task):
        if not task.done() and sys.gettrace() is None:
            info["cancelled"] = True
            task.cancel()

**Comment by delfick** [comment]
ooooh, that does look nice. I'll likely get that merged in when I'm next at
my computer. Thanks!

**Comment by delfick** [comment]
I've released 0.7.2 with that change @Aran-Fey, thanks for the suggestion!

> and even then the way a timeout interrupts a task means I don't think 

Seems my memory of this code when I was replying via emails from my phone wasn't overly accurate hahahha

**Comment by quantitative-technologies** [comment]
Sorry if this is an obvious question, but is there a way to configure the timeout so I don't need `@pytest.mark.async_timeout(1e10)` on all of my long-running tests, i.e. I want to turn off the timeout function for all tests?

**Comment by delfick** [comment]
@quantitative-technologies hello, yeap, there's a pytest option called "default_async_timeout" you can set, or even from the cli with the "--default-async-timeout" flag :)

**Comment by quantitative-technologies** [comment]
@delfick Thanks :)
