### ISSUE TITLE
How is it different!

### ISSUE THREAD

**Issue by dimaqq** [delfick/alt-pytest-asyncio#2]
Yay, excited to see someone taking up the task of writing better asyncio pytest plugin!

I think it would help casual users if there was a comparison against `pytest-asyncio` in the readme / on pypi.

How is it different? mindset? api? implementation? features? etc... 🙏

**Comment by delfick** [comment]
Thanks :)

The top of the readme explains what's different. It's mostly the same but
with some minor differences in tradeoffs

**Comment by delfick** [comment]
thanks :)
