### ISSUE TITLE
Allow setting default_alt_async_timeout using a CLI flag or an env variable

### ISSUE THREAD

**Issue by OrBin** [delfick/alt-pytest-asyncio#4]
Hi,
It would be great if we could set the global `default_alt_async_timeout` not only from _pytest.ini_, but also:

- from a CLI flag (something like `pytest --alt-async-timeout=60 my_test.py`) 
or
- from an environment variable (something like `ALT_ASYNC_TIMEOUT=60 pytest my_test.py`)

Any of these would be great.
Thanks

**Comment by delfick** [comment]
Hello,

I believe you should already be able to say [--default-async-timeout](https://github.com/delfick/alt-pytest-asyncio/blob/main/alt_pytest_asyncio/__init__.py#L15)

**Comment by OrBin** [comment]
Cool! But it seems like you didn't release a version with this change: the latest version in PyPI is 0.5.3, from July 25th, while this feature was added on August 24th. Do you plan to release it soon?

**Comment by OrBin** [comment]
Cool! But it seems like you didn't release a version with this change: the latest version in PyPI is 0.5.3, from July 25th, while this feature was added on August 24th. Do you plan to release it soon?

**Comment by delfick** [comment]
hmmm, you're correct. I'll release a new version with this change :)

Probably later today or tomorrow.

**Comment by OrBin** [comment]
Great, thanks

**Comment by delfick** [comment]
I've released 0.5.4 https://pypi.org/project/alt-pytest-asyncio/ :)

**Comment by OrBin** [comment]
Works well, thanks! Also, maybe you'd like to inform in the release notes that you renamed the configuration variables (`default_alt_async_timeout`->`default_async_timeout`).

**Comment by delfick** [comment]
hmm, this was contributed to the project a while ago, I forgot the option changed name. Possibly should have made it 0.6 instead of 0.5.4. oops.

I've changed the readme, thank for pointing that out.
