### ISSUE TITLE
Allow setting a timeout for test setup

### ISSUE THREAD

**Issue by OrBin** [delfick/alt-pytest-asyncio#6]
Setting a timeout for tests is great, but it would be more useful if we could also set a timeout for the test setup (and test teardown too).
It may be a different CLI flag/configuration key than the existing one.

[pytest-timeouts](https://pytest-timeouts.readthedocs.io/en/latest/usage/) implements such a feature, but is not maintained any more; see their implementation [here](https://github.com/Scony/pytest-timeouts/blob/32b58c4ba8736772191ac103ef51a466f7d09bb6/pytest_timeouts.py#L164).

Thanks.

**Comment by delfick** [comment]
Oh yeah, so a separate default for setup/teardown? Currently they use the same default you set for tests and can be overridden with a `pytest.mark.async_timeout` decorator on the fixture

**Comment by delfick** [comment]
So basically here get two timeouts, one for setup and one for teardown https://github.com/delfick/alt-pytest-asyncio/blob/main/alt_pytest_asyncio/async_converters.py#L181

Make a separate mark for `async_setup_timeout` and `async_teardown_timeout` and default to the current way of finding a timeout if those aren't set.

I'm very swamped at the moment, so I'm not sure when I'll have time to have a look, but I'll add it to the list of things.

**Comment by OrBin** [comment]
Are you sure? I have an async test getting stuck on setup without timing
out, and I do have a default timeout which successfully makes the tests
time out.

**Comment by delfick** [comment]
Seems to work for me

Is your setup function ignoring the asyncio.CancelledError ?

<img width="1270" alt="Screen Shot 2021-06-24 at 8 59 32 am" src="https://user-images.githubusercontent.com/109301/123178430-8680c380-d4ca-11eb-8d33-eff3a1cdd173.png">

**Comment by OrBin** [comment]
Sorry, I can't find any reference to either `async_setup_timeout` or `async_teardown_timeout` in the repo, can you direct me to where it's used? Or did you mean I should create it myself and set the timeout myself? Not sure I understood.

Regarding your example, here you show how to set a timeout for a fixture, but I mean a timeout for the whole test setup process.
To you question, I don't think my setup function is ignoring `asyncio.CancelledError`.

**Comment by delfick** [comment]
Yeah, as in they'd have to be added in the same way we add this https://github.com/delfick/alt-pytest-asyncio/blob/main/alt_pytest_asyncio/__init__.py#L17

> Regarding your example, here you show how to set a timeout for a fixture, but I mean a timeout for the whole test setup process.

Oh, right, I see. I didn't realise pytest had that. In that case I'd have to explore it a bit further. Which I have even less time for at the moment sorry. I'll happily look at PRs though if you or anyone else can figure it out in the meantime

> To you question, I don't think my setup function is ignoring asyncio.CancelledError

And it's an async setup function doing async things?

**Comment by OrBin** [comment]
> And it's an async setup function doing async things?
No, it's synchronous, but I have an issue of DB locks in my tests that I want to work around, in a way that such a lock reaches a timeout rather than runs forever. It's not really related to async code, but I already use _alt-pytest-asyncio_ for test timeouts.

**Comment by delfick** [comment]
right. The way asyncio cancellation works only works on other async code

**Comment by OrBin** [comment]
I see. So I guess the best I can do is either use `pytest-timeouts` or
implement such a timeout myself.

**Comment by delfick** [comment]
Mixing async and sync code is problematic because async is single threaded. So whilst your sync code is doing anything it's gonna stop async doing anything else.

So you'd need something like [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) to run your sync code in a thread. You can then make your sync code have something like a [threading.Event object](https://docs.python.org/3/library/threading.html#event-objects) that you set when you receive an asyncio.CancelledError and it's up to your sync code to look at it every so often to see if it should stop what it's doing.
