### ISSUE TITLE
Adopt Poetry as package manager and Makefile to hold scripts

### ISSUE THREAD

**Issue by andredias** [delfick/alt-pytest-asyncio#7]
I wonder if you are interested in adopting Poetry as the package management tool. It could also replace `setup.py`.

In addition, I'd also include a `Makefile` to store all development task scripts in one single file. I believe it would make the project simpler.

I contributed to another project recently with changes these: https://github.com/sabuhish/fastapi-mail/pull/89

**Comment by delfick** [comment]
Hello,

Thanks for the suggestion. I'm not a fan of poetry (tbf, haven't given it much of a chance) but I especially think for libraries, a setup.py is more appropriate.

Poetry tends to be more for applications than libraries.

And I also prefer separate scripts than a Makefile. Those tend to get quite messy and I almost never need more than the `format`, `lint`, `test.sh` trio I have in all my projects.

**Comment by delfick** [comment]
Also, sorry I was abrupt the other day. I was gonna ask if you wanted to make a change and then forgot. I imagine it was to play with the context vars?

**Comment by andredias** [comment]
No problem. This issue is not related to the other one #8
